name: Get Images

on:
  repository_dispatch:
    types: [ get-image ]
  push:
    branches:
      - master
    paths:
      - 'image-info.json'
      - 'image-list.json'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Download Image
      run: |
        yarn --frozen-lockfile
        yarn get
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Save origin images
        target_branch: origin
        build_dir: origin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Repository Dispatch
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: update-image
